# Menu config
# 菜单配置

[[main]]
  identifier = "posts"
  name = "Blog"
  url = "/posts/"
  title = ""
  weight = 1

[[main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  title = ""
  weight = 2

[[main]]
  identifier = "cv"
  pre = ""
  post = ""
  name = "CV"
  url = "/cv/"
  title = "Curriculum Vitae"
  weight = 4 
[[main]]
  identifier = "contact"
  pre = ""
  post = ""
  name = "Contact"
  url = "/contact/"
  title = ""
  weight = 5


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Privacy"
   pageRef = "privacy"
   weight = 10

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 20   


 [[footer]]
   name = "Categories"
   pageRef = "categories"
   weight = 30   


 [[footer]]
   name = "Contact"
   pageRef = "contact"
   weight = 40

 [[footer]]
   name = "RSS"
   url = "/index.xml"
   weight = 50